[#7]FEAT(Create Class): create class and class details page
OBQA-DLSU/web-ui pull request #79
Opened 2017-12-28 19:54 UTC by irvinalfaro11

2017-12-28 20:02 UTC, irvinalfaro11 commented
format adjusted  and removed unnecessary comments and files

2017-12-28 20:16 UTC, johnhigginsavila requested changes
- User *ngFor for select tags

2017-12-28 20:16 UTC, johnhigginsavila commented on src/app/class/add-class/add-class.component.html
> +                        <mat-option value="1">Term 1</mat-option>
use *ngFor

2017-12-28 20:16 UTC, johnhigginsavila commented on src/app/class/add-class/add-class.component.html
> +                    <mat-select placeholder="Cycle"  formControlName="cycle">
use *ngFor

2017-12-30 03:19 UTC, johnhigginsavila approved these changes
-LGTM

2017-12-30 03:23 UTC, merged